import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import React from 'react'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

        <body className={inter.className}>
        <div className={'bg-zinc-100 border-b px-8 py-2'}>
            <p className={'font-semibold text-2xl'}>Financial tracker</p>
        </div>
        {children}
        </body>
        </html>
    )
}
